server:
  port: 8080
spring:
  application:
    name: example-ia
  ai:
    #Azure
#    azure:
#      openai:
#        api-key: ${AZURE_OPENAI_API_KEY}
#        endpoint: ${AZURE_OPENAI_ENDPOINT}
#        model: ${AZURE_OPENAI_MODEL}
    #Open AI
    openai:
      api-key: API_KEY
      chat:
        options:
          model: gpt-3.5-turbo # defautl option
